import { supabase } from '@/lib/supabase';

export async function fetchCFOMetrics() {
  try {
    // 1. Try fetching from v3 schema tables first
    let { data: revenue } = await supabase.from('revenue_records').select('amount');
    let { data: expenses } = await supabase.from('expenses').select('amount');
    let { data: payroll } = await supabase.from('payroll_records').select('amount, status');
    let { data: invoices } = await supabase.from('invoices').select('amount, total_amount, status');

    // 2. If v3 schema is empty or missing, fallback to v2 schema tables (ledger and invoices)
    let totalRevenue = (revenue || []).reduce((acc, curr) => acc + Number(curr.amount || 0), 0);
    let totalExpense = (expenses || []).reduce((acc, curr) => acc + Number(curr.amount || 0), 0);

    if (totalRevenue === 0 && totalExpense === 0) {
      // Try fallback to ledger table from v2 schema
      const { data: ledgerEntries } = await supabase.from('ledger').select('amount, credit, debit, account_category');
      if (ledgerEntries && ledgerEntries.length > 0) {
        ledgerEntries.forEach(item => {
          const amt = Number(item.amount || item.credit || item.debit || 0);
          if (item.account_category === 'revenue') totalRevenue += amt;
          if (item.account_category === 'expense') totalExpense += amt;
        });
      }
    }

    // Invoices fallback for payroll/liability calculations if payroll_records is empty
    let pendingPayroll = (payroll || [])
      .filter(p => p.status === 'unpaid' || p.status === 'upcoming')
      .reduce((acc, curr) => acc + Number(curr.amount || 0), 0);

    if (pendingPayroll === 0 && invoices && invoices.length > 0) {
      pendingPayroll = invoices
        .filter(i => i.status === 'overdue' || i.status === 'sent')
        .reduce((acc, curr) => acc + Number(curr.amount || curr.total_amount || 0), 0);
    }

    const netProfit = totalRevenue - totalExpense;

    let revenueEfficiency = "N/A";
    if (totalExpense > 0) {
      revenueEfficiency = (totalRevenue / totalExpense).toFixed(1) + "x";
    } else if (totalRevenue > 0) {
      revenueEfficiency = "MAX";
    }

    const healthScore = netProfit > 0 ? "A+" : totalRevenue === 0 ? "N/A" : "C-";

    // 3. Time-Series data logic
    const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const monthlyData: Record<string, { revenue: number, expense: number }> = {};
    monthNames.forEach(m => monthlyData[m] = { revenue: 0, expense: 0 });

    const { data: timeSeriesRevenue } = await supabase.from('revenue_records').select('amount, recorded_at');
    const { data: timeSeriesExpense } = await supabase.from('expenses').select('amount, date');

    (timeSeriesRevenue || []).forEach(r => {
      if (r.recorded_at) {
        const date = new Date(r.recorded_at);
        const month = monthNames[date.getMonth()];
        monthlyData[month].revenue += Number(r.amount || 0);
      }
    });

    (timeSeriesExpense || []).forEach(e => {
      if (e.date) {
        const date = new Date(e.date);
        const month = monthNames[date.getMonth()];
        monthlyData[month].expense += Number(e.amount || 0);
      }
    });

    const chartData = Object.keys(monthlyData).map(key => ({
      name: key,
      value: monthlyData[key].revenue - monthlyData[key].expense
    }));

    // 4. AI Recommendations safely
    const { data: aiRecs } = await supabase.from('ai_recommendations').select('*').eq('status', 'active');

    const recordCount = (revenue?.length || 0) + (expenses?.length || 0) + (payroll?.length || 0) + (invoices?.length || 0);

    return {
      netProfit,
      payrollLiability: pendingPayroll,
      revenueEfficiency,
      healthScore,
      chartData: chartData.filter(d => d.value !== 0),
      aiRecommendations: aiRecs || [],
      recordCount
    };
  } catch (err) {
    console.error("fetchCFOMetrics error:", err);
    return {
      netProfit: 0,
      payrollLiability: 0,
      revenueEfficiency: "N/A",
      healthScore: "N/A",
      chartData: [],
      aiRecommendations: [],
      recordCount: 0
    };
  }
}

export async function generateReport(metrics?: any) {
  // Generate a real text report
  const reportContent = `SCOMS CFO Intelligence Report
Date: ${new Date().toLocaleDateString()}
----------------------------------------
Net Profit: $${metrics?.netProfit || 0}
Payroll Liability: $${metrics?.payrollLiability || 0}
Revenue Efficiency: ${metrics?.revenueEfficiency || 'N/A'}
Health Score: ${metrics?.healthScore || 'N/A'}
----------------------------------------
Report automatically generated by AI CFO Engine.`;

  const blob = new Blob([reportContent], { type: 'text/plain' });
  const fileName = `cfo_reports/cfo_report_${Date.now()}.txt`;
  
  // Upload to Supabase Storage
  let reportUrl = "";
  const { data: uploadData, error: uploadError } = await supabase.storage
    .from('documents')
    .upload(fileName, blob, { upsert: true });
    
  if (!uploadError && uploadData) {
    const { data: urlData } = supabase.storage.from('documents').getPublicUrl(fileName);
    reportUrl = urlData?.publicUrl || "";
  } else {
    console.warn("Storage upload failed, falling back to local object URL:", uploadError?.message);
    reportUrl = URL.createObjectURL(blob);
  }
  
  const { data, error } = await supabase.from('generated_reports').insert([{
    report_name: `CFO Intelligence Report - ${new Date().toLocaleDateString()}`,
    report_type: 'cfo_summary',
    file_url: reportUrl
  }]);
  
  if (error) {
    console.warn("Insert into generated_reports restricted by RLS:", error.message);
  }
  return reportUrl;
}
